### PR TITLE
Fixed No Storage + No Ack

### PR DESCRIPTION
**Pull request by amark**
I guess I should have done this on a branch, woops sorry.

I tested this code in my local edits with the browser test and it worked, this PR is hand-copy of that, so if I didn't typo anything it should work, but if it does not work don't have worry/fear just a typo I might have missed, it'll be easy to adjust - let me know.

### CODE REVIEW

**Comment by jabis** [comment]
Hi @amark the `gun.user().put` don't go thru checkout relevant branch
https://github.com/meething/gundb-multisocket/blob/nomem-user-bug/server.js#L103

**Comment by amark** [comment]
@jabis I couldn't replicate :( tho I still assume I'm doing something wrong.

I tried to hastily modify and test something:

https://pastebin.com/CwF91c3b

That ^ worked as well.

Maybe help me figure out how I can replicate and get it to fail? I assume I'm wrong.

 + shouldn't password only be browser/client side?

**Comment by jabis** [comment]
@amark no - the room creation is supposed to be serverside, server creates the room and assigns it to the 
```js   
var pwprotected =  gun.user().get(roomname).put(roomobjy); // and puts that into  
gun.get("rtcmeeting").get(roomname).put(pwprotected), 
```  
uses the creators PoW hash passed as `sig` as password, clientside all users gain access to the room object against a password field  
```js  
var hash = SEA.work({room:roomname, roompass:passwordfield.value},passwordfield.value,null,{name:'SHA-256'});
user.auth(roomname,hash); 
```  
derived PoW hash to have access to write to the room object

**Comment by jabis** [comment]
GH key commands pardon for toggling >.<

**Comment by jabis** [comment]
@amark, do note that the gun.user() system is DEAD both on server and clientside, you can't create a user from either 
image

**Comment by amark** [comment]
@jabis oh my comment is stale/out dated, I gave updates in Meething discord ... have you been able to check those?

**Comment by jabis** [comment]
I just woke up, will fire up discord in a sec, ran your test too and no it doesn't go thru - {err:undefined}

image

**Comment by amark** [comment]
@jabis right that test is also messed now after I found... I found out that months ago when I updated `stats` to report stats/errors in the HTML dashboard... it started swallowing errors, so thats why it is isn't working & you'd have no clue cause it isn't reporting it to you so sorry & ... see chat

**Comment by lmangani** [comment]
Although this is not complete, we're merging it already due to the master one being severely broken. @jabis @amark TBC

**Pull request merged**
